The purpose of this notebooks is to explore advanced queries of the STREAM data.

In [75]:
from utils import S3hsclient

In [76]:
hs = S3hsclient.S3HydroShare()

Please Enter Your HydroShare Credentials

Username:  TonyCastronova
Password for TonyCastronova:  ········

MRB data exists in HydroShare at: https://hydroshare.org/resource/9fc3a923419640729b1606f0e64bd288/. To load these data, we'll use the HydroShare Python library.

In [77]:
resource_id = '9fc3a923419640729b1606f0e64bd288'
resource = hs.resource(resource_id)

This resource contains a number of files that can be loaded for analysis. To see which files are available we'll use the `ls` command.

In [78]:
resource.s3_ls()

['tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/dynamic_antropogenic.parquet',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/gauges.cpg',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/gauges.dbf',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/gauges.parquet',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/gauges.prj',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/gauges.shp',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/gauges.shx',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/grab_samples.parquet',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/lulc.parquet',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/metadata.parquet',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/streamflow',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/vaa.parquet',
 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/water_quality']

## Multi-Filter Query

In [104]:
import pyarrow.dataset as ds
from functools import reduce
from datetime import datetime

Create a dictionary of the files shown above to make them easier to work with in Python.

In [105]:

files = {
     'metadata': 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/metadata.parquet',
     'vaa': 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/vaa.parquet',
     'water_quality': 'tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/water_quality'
}

Benchmark querying data using joined dask dataframe

In [108]:
%%time

# Loop over the files above and load each file lazily
dfs = [
    dd.read_parquet(
        files[k],
        engine="pyarrow",
        filesystem=hs.get_s3_filesystem()
    )
    for k in ['metadata', 'vaa']
]

# merge the metadata and vaa files togther using the common "STREAM_ID" column
dat = reduce(lambda left, right: left.merge(right, on="STREAM_ID", how="inner"), dfs)


# perform some sort of filtering. In this example, we're isolating
# all STREAM_IDs that have a drainage areas less that 100 sqkm and 
# are within there 050100 HUC06 boundary.
dat = dat[
    (dat.drainagearea_sqkm_x <= 100) \
  & (dat.huc06 == "050100")
    ]

# so far everthing has been lazy, meaning that a computation hasn't
# taken place yet. Call the .compute() function to tell dask to
# execute the steps above and return back the resulting data.
dat = dat.compute()

dat

CPU times: user 106 ms, sys: 10.1 ms, total: 116 ms
Wall time: 811 ms

,STREAM_ID,sourceID,source,site name,latitude_wgs84,longitude_wgs84,drainagearea_sqkm_x,state_name_x,time_zone,WQ_parameters,...,nhdv2_comid,WTemp_C_count,SpC_uScm_count,DO_mgL_count,pH_count,Turb_FNU_count,Turb_NTU_count,NO3_mgNL_count,fDOM_QSU_count,fDOM_RFU_count
8,STREAM-gauge-1730,3022540,USGS,"Woodcock Creek at Blooming Valley, PA",41.690612,-80.048112,80.548689,Pennsylvania,Eastern,WTemp_C,...,9050351,102483.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,STREAM-gauge-1732,3026480,USGS,"East Branch Clarion River near Clermont, PA",41.644056,-78.531444,21.548717,Pennsylvania,Eastern,WTemp_C,...,6874075,112492.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Our query isolated two STREAM_IDs that fit our criteria. We'll now use these specific STREAM_IDs to collect the data we're interested in, for example all of the water quality observations associated with them.

In [110]:
%%time

import pyarrow.dataset as ds

dataset = ds.dataset(
    files['water_quality'],
    format="parquet",
    filesystem=hs.get_s3_filesystem(),
    partitioning="hive"
)
stream_ids = list(dat.STREAM_ID) # returned from cell above
result = dataset.to_table(
    filter=(
        (ds.field("STREAM_ID").isin(stream_ids))
    )
)
df = result.to_pandas()
df

CPU times: user 232 ms, sys: 58 ms, total: 290 ms
Wall time: 1.66 s

,DateTime,WTemp_C,Flag_WTemp_C,SpC_uScm,Flag_SpC_uScm,DO_mgL,Flag_DO_mgL,pH,Flag_pH,Turb_FNU,...,Flag_Turb_NTU,fDOM_QSU,Flag_fDOM_QSU,Chla_ugL,Flag_Chla_ugL,PC_RFU,Flag_PC_RFU,fDOM_RFU,Flag_fDOM_RFU,STREAM_ID
0,2013-08-09 04:00:00,20.350,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STREAM-gauge-1730
1,2013-08-09 05:00:00,20.225,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STREAM-gauge-1730
2,2013-08-09 06:00:00,20.100,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STREAM-gauge-1730
3,2013-08-09 07:00:00,20.025,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STREAM-gauge-1730
4,2013-08-09 08:00:00,19.925,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STREAM-gauge-1730
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112487,2025-08-10 14:00:00,17.700,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STREAM-gauge-1732
112488,2025-08-10 15:00:00,17.825,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STREAM-gauge-1732
112489,2025-08-10 16:00:00,18.000,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STREAM-gauge-1732
112490,2025-08-10 17:00:00,18.300,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STREAM-gauge-1732
112491,2025-08-10 18:00:00,18.675,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,STREAM-gauge-1732

## (TESTING) Multi-file Loading using PyArrow Dataset

In [111]:
import pyarrow.dataset as ds

In [113]:
# List of original Parquet files
files = {
    "dynamic_anthropogenic": "tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/dynamic_antropogenic.parquet",
    "gauges": "tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/gauges.parquet",
    "grab_samples": "tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/grab_samples.parquet",
    "lulc": "tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/lulc.parquet",
    "streamflow": "tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/streamflow",
    "water_quality": "tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/water_quality",
    "metadata": "tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/metadata.parquet",
    "vaa": "tonycastronova/9fc3a923419640729b1606f0e64bd288/data/contents/vaa.parquet",
}

In [18]:
# Create a dataset pointing to the files
dataset = ds.dataset(files,
                     format="parquet",
                     filesystem=hs.get_s3_filesystem() 
                    )

# Save a reference to disk (virtual dataset)
#ds.write_dataset(dataset, base_dir="/path/to/virtual_dataset", format="parquet")

In [25]:
ds.dataset(files[7],
                     format="parquet",
                     filesystem=hs.get_s3_filesystem() 
                    ).schema

STREAM_ID: large_string
state_name: large_string
drainagearea_sqkm: double
huc12: large_string
huc10: large_string
huc08: large_string
huc06: large_string
huc04: large_string
huc02: large_string
nhdv2_comid: large_string
WTemp_C_count: double
SpC_uScm_count: double
DO_mgL_count: double
pH_count: double
Turb_FNU_count: double
Turb_NTU_count: double
NO3_mgNL_count: double
fDOM_QSU_count: double
fDOM_RFU_count: double
-- schema metadata --
pandas: '{"index_columns": [{"kind": "range", "name": null, "start": 0, "' + 2538